version: '3'

services:
  bib2rdf:
    build: './bib2rdf'
    command: ["http://example.org/bib/"]
    volumes:
      - datavolume:/data
      # Mount BibTeX file from host
      - ./resources/aksw.bib:/data/bibtex.bib

  shacl:
    build: './shacl'
    volumes:
      - datavolume:/data
    depends_on:
      - bib2rdf
      - mongo

volumes:
  datavolume: