version: '3'

services:
  bib2rdf:
    build: './bib2rdf'
    command: ["http://example.org/bib/"]
    volumes:
      - datavolume:/data
      # Mount BibTeX file from host
      - ./resources/aksw.bib:/data/bibtex.bib

  shacl:
    build: './shacl'
    entrypoint: ["./wait-for-it.sh","--strict","--timeout=0","www.wikipedia.com:80","--"]
    command: echo 'test'
    volumes:
      - datavolume:/data
    depends_on:
      - bib2rdf

volumes:
  datavolume: