version: '3'

services:
  bib2rdf:
    build: './bib2rdf'
    volumes:
      - datavolume:/data
      # Mount BibTeX file from host to volume
      - ./resources/aksw.bib:/data/bibtex.bib

  shifter:
    build: './shifter'
    volumes: 
      - datavolume:/data
      # Mount schema.map file from host to volume
      - ./bib2rdf/schema.map:/data/schema.map

  shacl:
    build: './shacl'
    # Wait for files from 'bib2rdf' and 'shifter' using dockerize
    entrypoint: [
      "dockerize",
      "-wait","file:///data/bibtex.rdf",
      "-wait","file:///data/shapes.ttl",
      "-timeout","10m",
      "pyshacl"]
    command: ["-s","/data/shapes.ttl","-m","-i","rdfs","-a","-f","human","/data/bibtex.rdf"]
    volumes:
      - datavolume:/data
    depends_on:
      - bib2rdf
      - shifter

volumes:
  datavolume: