version: '3'

services:
  bib2rdf:
    build: './bib2rdf'
    command: ["http://example.org/bib/"]
    volumes:
      - datavolume:/data
      # Mount BibTeX file from host to volume
      - ./resources/aksw.bib:/data/bibtex.bib

  shacl:
    build: './shacl'
    # Wait for file from 'bib2rdf' using dockerize
    entrypoint: ["dockerize","-wait","file:///data/bibtex.rdf","-timeout","1h",
      "pyshacl","-s","ex_shape.ttl","-m","-i","rdfs","-a","-f","human","/data/bibtex.rdf"]
    volumes:
      - datavolume:/data
    depends_on:
      - bib2rdf

volumes:
  datavolume: