version: '3'

services:
  webhookd:
    build:
      dockerfile: "./webhookd/Dockerfile"
      context: "."
    ports:
      - "9000:9000"
    environment:
      # Pass special project name to sparate network etc.
      - COMPOSE_PROJECT_NAME=deploy-shapbird
      # Pass the host PWD for docker daemon volume mounting
      - HOST_PWD=${PWD}
    volumes:
      # Docker daemon from host
      - /var/run/docker.sock:/var/run/docker.sock

  n8n:
    build: './n8n'
    ports:
      - "5678:5678"
    depends_on:
      - webhookd
